name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          ./venv/bin/pip install -r requirements.txt pytest pytest-html
          ./venv/bin/python -m pytest --html=report.html -p no:warnings

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: pytest-report
          path: report.html
